[package]
name = "math"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4.0"
nalgebra = "0.32.1"
num-traits = "0.2.15"
rand = "0.8.5"

